export const playlistRouteTypes = {
    CREATE_PLAYLIST:"CREATE_PLAYLIST",
    ADD_SONG_TO_PLAYLIST:"ADD_SONG_TO_PLAYLIST",
    REMOVE_SONG_FROM_PLAYLIST:"REMOVE_SONG_FROM_PLAYLIST",
    TOGGLE_LIKED_SONG:"TOGGLE_LIKED_SONG",
}