import Head from "next/head";
import { AudioPlayer } from "../components/AudioPlayer/AudioPlayer";
import styles from "../styles/Home.module.scss";
import { getProviders, signIn } from "next-auth/react";


export default function Home({providers}) {




  return (
    <div className={styles.container}>
      <Head>
        <title>React audio Player</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <button onClick={() => signIn("dropbox")}>sign in</button>
        <AudioPlayer
          title="This is a long long long long long skhfakajfh title"
          artist="Maxime Légaré"
          fileUrl="http://u.pc.cd/VUgrtalK"
          imgUrl="https://upload.wikimedia.org/wikipedia/en/8/8e/World_Domination_%28Band-Maid_album%29.png"
        />
      </main>
    </div>
  );
}



